var searchData=
[
  ['budowniczystatkow_78',['BudowniczyStatkow',['../namespace_gra_w_statki_logika_1_1_plansza_bitwy_1_1_budowniczy_statkow.html',1,'GraWStatkiLogika::PlanszaBitwy']]],
  ['g_5fkomputer_79',['G_Komputer',['../class_gra_w_statki_front_1_1_komputer_1_1_g___komputer.html',1,'GraWStatkiFront.Komputer.G_Komputer'],['../class_gra_w_statki_front_1_1_komputer_1_1_g___komputer.html#a300d4755a74653cb3c7fd9df6575266b',1,'GraWStatkiFront.Komputer.G_Komputer.G_Komputer()']]],
  ['g_5fkomputer_2ecs_80',['G_Komputer.cs',['../_g___komputer_8cs.html',1,'']]],
  ['g_5fkontrolagry_81',['G_KontrolaGry',['../class_gra_w_statki_front_1_1_kontrola_gry_1_1_g___kontrola_gry.html',1,'GraWStatkiFront.KontrolaGry.G_KontrolaGry'],['../class_gra_w_statki_front_1_1_kontrola_gry_1_1_g___kontrola_gry.html#a4f6aac1821a54002d5d7712d82dba44f',1,'GraWStatkiFront.KontrolaGry.G_KontrolaGry.G_KontrolaGry()']]],
  ['g_5fplanszabitwy_82',['G_PlanszaBitwy',['../class_gra_w_statki_front_1_1_plansza_bitwy_1_1_g___plansza_bitwy.html',1,'GraWStatkiFront.PlanszaBitwy.G_PlanszaBitwy'],['../class_gra_w_statki_front_1_1_plansza_bitwy_1_1_g___plansza_bitwy.html#a47d318060ec077031c7cfbf7b0678abf',1,'GraWStatkiFront.PlanszaBitwy.G_PlanszaBitwy.G_PlanszaBitwy()']]],
  ['getkolumna_83',['GetKolumna',['../class_gra_w_statki_front_1_1_plansza_bitwy_1_1_g___plansza_bitwy.html#a627532acc51f3cdd9b67fcecd9b014bc',1,'GraWStatkiFront::PlanszaBitwy::G_PlanszaBitwy']]],
  ['getwiersz_84',['GetWiersz',['../class_gra_w_statki_front_1_1_plansza_bitwy_1_1_g___plansza_bitwy.html#a169b6ae61e5b90c0d3a8ca0913a2dba1',1,'GraWStatkiFront::PlanszaBitwy::G_PlanszaBitwy']]],
  ['gora_85',['Gora',['../namespace_gra_w_statki_logika_1_1_plansza_bitwy.html#aa5623e56327ecf190e03a035455ce689a858d01562d1a6d69cc0f8daaf8f27a96',1,'GraWStatkiLogika::PlanszaBitwy']]],
  ['gplanszagracza_86',['gPlanszaGracza',['../class_gra_w_statki_front_1_1_kontrola_gry_1_1_g___kontrola_gry.html#a69dca3deb84aa12dfe46debe118bbcee',1,'GraWStatkiFront::KontrolaGry::G_KontrolaGry']]],
  ['gplanszakomputera_87',['gPlanszaKomputera',['../class_gra_w_statki_front_1_1_kontrola_gry_1_1_g___kontrola_gry.html#ad521d16de880ff524b8297c5b9a4c678',1,'GraWStatkiFront::KontrolaGry::G_KontrolaGry']]],
  ['gracz_88',['Gracz',['../class_gra_w_statki_logika_1_1_kontrola_gry_1_1_l___gra.html#acccd135c75c6b3b9c4da66ffa072031a',1,'GraWStatkiLogika::KontrolaGry::L_Gra']]],
  ['graskonczona_89',['GraSkonczona',['../class_gra_w_statki_logika_1_1_kontrola_gry_1_1_l___kontroler_gry.html#a392850513495cd87b195e2e6a1b40fe4',1,'GraWStatkiLogika::KontrolaGry::L_KontrolerGry']]],
  ['grawstatki_90',['GraWStatki',['../namespace_gra_w_statki.html',1,'']]],
  ['grawstatki_2ecsproj_2efilelistabsolute_2etxt_91',['GraWStatki.csproj.FileListAbsolute.txt',['../_debug_2_gra_w_statki_8csproj_8_file_list_absolute_8txt.html',1,'(Global Namespace)'],['../_release_2_gra_w_statki_8csproj_8_file_list_absolute_8txt.html',1,'(Global Namespace)']]],
  ['grawstatkifront_92',['GraWStatkiFront',['../namespace_gra_w_statki_front.html',1,'']]],
  ['grawstatkifront_2eassemblyinfo_2ecs_93',['GraWStatkiFront.AssemblyInfo.cs',['../_debug_2netstandard2_80_2_gra_w_statki_front_8_assembly_info_8cs.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_gra_w_statki_front_8_assembly_info_8cs.html',1,'(Global Namespace)']]],
  ['grawstatkifront_2ecsproj_2efilelistabsolute_2etxt_94',['GraWStatkiFront.csproj.FileListAbsolute.txt',['../_debug_2netstandard2_80_2_gra_w_statki_front_8csproj_8_file_list_absolute_8txt.html',1,'(Global Namespace)'],['../_release_2netstandard2_80_2_gra_w_statki_front_8csproj_8_file_list_absolute_8txt.html',1,'(Global Namespace)']]],
  ['grawstatkilogika_95',['GraWStatkiLogika',['../namespace_gra_w_statki_logika.html',1,'']]],
  ['grawstatkilogika_2ecsproj_2efilelistabsolute_2etxt_96',['GraWStatkiLogika.csproj.FileListAbsolute.txt',['../_debug_2_gra_w_statki_logika_8csproj_8_file_list_absolute_8txt.html',1,'(Global Namespace)'],['../_release_2_gra_w_statki_logika_8csproj_8_file_list_absolute_8txt.html',1,'(Global Namespace)']]],
  ['grawstatkitesty_97',['GraWStatkiTesty',['../namespace_gra_w_statki_testy.html',1,'']]],
  ['grawstatkitesty_2ecsproj_2efilelistabsolute_2etxt_98',['GraWStatkiTesty.csproj.FileListAbsolute.txt',['../_gra_w_statki_testy_8csproj_8_file_list_absolute_8txt.html',1,'']]],
  ['komputer_99',['Komputer',['../namespace_gra_w_statki_front_1_1_komputer.html',1,'GraWStatkiFront.Komputer'],['../namespace_gra_w_statki_logika_1_1_komputer.html',1,'GraWStatkiLogika.Komputer']]],
  ['kontrolagry_100',['KontrolaGry',['../namespace_gra_w_statki_front_1_1_kontrola_gry.html',1,'GraWStatkiFront.KontrolaGry'],['../namespace_gra_w_statki_logika_1_1_kontrola_gry.html',1,'GraWStatkiLogika.KontrolaGry'],['../namespace_gra_w_statki_testy_1_1_kontrola_gry.html',1,'GraWStatkiTesty.KontrolaGry']]],
  ['planszabitwy_101',['PlanszaBitwy',['../namespace_gra_w_statki_front_1_1_plansza_bitwy.html',1,'GraWStatkiFront.PlanszaBitwy'],['../namespace_gra_w_statki_logika_1_1_plansza_bitwy.html',1,'GraWStatkiLogika.PlanszaBitwy'],['../namespace_gra_w_statki_testy_1_1_plansza_bitwy.html',1,'GraWStatkiTesty.PlanszaBitwy']]],
  ['pola_102',['Pola',['../namespace_gra_w_statki_logika_1_1_plansza_bitwy_1_1_pola.html',1,'GraWStatkiLogika::PlanszaBitwy']]],
  ['properties_103',['Properties',['../namespace_gra_w_statki_1_1_properties.html',1,'GraWStatki']]],
  ['statki_104',['Statki',['../namespace_gra_w_statki_logika_1_1_plansza_bitwy_1_1_statki.html',1,'GraWStatkiLogika::PlanszaBitwy']]]
];
